Use docker `exec` instead of `run`
`exec` is for running commands inside the existing container, `run` would actually create a new container and run the `kong reload` there ... which likely will fail like this:
~~~~
$ docker run -it kong kong reload
Unable to find image 'kong:latest' locally
Trying to pull repository docker.io/kong ... not found
Error: image library/kong:latest not found
$ docker run -it mashape/kong kong reload
[INFO] Using configuration: /etc/kong/kong.yml
[ERR] Could not reload: Kong is not running.
~~~~

(The first error would be because `run` wants an image name, not a container name; the second one then uses a suitable image name, but that one just doesn't have a kong running)